project:
  type: website

website:
  title: "Spotify Dashboard"
  favicon: images/logo.png
  page-navigation: true
  site-url: https://econmaett.github.io/spotify-dashboard
  repo-url: https://github.com/econmaett/spotify-dashboard
  repo-actions: [edit, source, issue]
  sidebar:
    title: "Spotify Dashboard"
    style: "docked"
    search: false
    collapse-level: 1
    logo: images/logo.png
    contents: 
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: [cosmo, custom.scss]
    highlight-style: atom-one-dark
    toc: true
    grid:
      sidebar-width: 150px



